services:
  
  applicationdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
