name: .NET CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Install dependencies
        run: dotnet restore ./HallandHideaways.sln

      - name: Build project
        run: dotnet build ./HallandHideaways.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./HallandHideaways.sln --configuration Release --no-restore --no-build
